# Generated by Django 5.0.4 on 2025-07-25 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='PRODUCT_IMAGES/')),
                ('quantity', models.IntegerField()),
                ('sku', models.CharField(max_length=12)),
                ('height_cm', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, help_text='Width in centimeters', max_digits=6)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, to='portal.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, to='portal.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('brand_name', 'owner')},
        ),
    ]
